### ISSUE TITLE
Main menu not loading on Linux

### ISSUE THREAD

**Issue by Zstorm999** [d-jackthenarrator/Civ6-MPH#6]
When I launch the game with the mod active, it's impossible to see the main menu, or to click on any button.

**Conditions of the bug:** 
I'm playing with the last version of the game, on Pop_OS! version 20.10, native Linux version (so no problem of compatibility coming from Proton)

**How to reproduce:**
Simply launch the game, splash screens are fine but it's impossible to see the main menu if the mod is active (from the steam workshop). 

I tried with other mods as well, and the problem is definitely coming from this one since the game launches correctly with them.

Hoping for a quick fix

**Comment by d-jackthenarrator** [comment]
Yes it is path finding with Linux being case sensitive :( It is a pain to debug with windows

**Comment by enderger** [comment]
I'm working on a fix now!

**Comment by enderger** [comment]
@Zstorm999 It should now be working, the current workshop version functions on my NixOS machine.
